CREATE TABLE short_urls
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_key    VARCHAR(255)                            NOT NULL,
    original_url VARCHAR(255)                            NOT NULL,
    created_by   BIGINT,
    is_private   BOOLEAN,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    expires_at   TIMESTAMP WITHOUT TIME ZONE,
    click_count  BIGINT,
    CONSTRAINT pk_short_urls PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE short_urls
    ADD CONSTRAINT uc_short_urls_shortkey UNIQUE (short_key);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE short_urls
    ADD CONSTRAINT FK_SHORT_URLS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);